// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYBMHgUsk5bqx2FZpiqza2zoj7q0CTMNk',
    appId: '1:988054722403:web:9e628d1a4eeb63e00ae556',
    messagingSenderId: '988054722403',
    projectId: 'flutter-firebase-integra-b9a6b',
    authDomain: 'flutter-firebase-integra-b9a6b.firebaseapp.com',
    storageBucket: 'flutter-firebase-integra-b9a6b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTzAUXvdgv5b9lbmJnQz3vwckNUhfRfbc',
    appId: '1:988054722403:android:daece77053d52bc50ae556',
    messagingSenderId: '988054722403',
    projectId: 'flutter-firebase-integra-b9a6b',
    storageBucket: 'flutter-firebase-integra-b9a6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcXxLOJKYbBTYvQk0pPGmfoAoM15Fjgyk',
    appId: '1:988054722403:ios:5cb483f8db2a306a0ae556',
    messagingSenderId: '988054722403',
    projectId: 'flutter-firebase-integra-b9a6b',
    storageBucket: 'flutter-firebase-integra-b9a6b.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseIntegration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcXxLOJKYbBTYvQk0pPGmfoAoM15Fjgyk',
    appId: '1:988054722403:ios:c5c5198238a762f70ae556',
    messagingSenderId: '988054722403',
    projectId: 'flutter-firebase-integra-b9a6b',
    storageBucket: 'flutter-firebase-integra-b9a6b.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseIntegration.RunnerTests',
  );
}
